### PR TITLE
Laser beams not just for sharks

### PR DESCRIPTION
**Pull request by missbassethorn**

### CODE REVIEW

**Comment by ammeep** [comment]
Yay!
Really want to merge this in but we have a merge conflict. If you want, I am chilling in the Ruby room - I can help you fix this up :+1:

Otherwise if you want to try and to fix it up on your own, try following the instructions here to update your fork with the changes in upstream https://help.github.com/articles/syncing-a-fork

Either way is fine - lemmie know :+1: 

stoked

**Comment by missbassethorn** [comment]
Oh noes!  Let me see if I can nut it out...

On 30 March 2014 15:15, Amy Palamountain notifications@github.com wrote:

> Yay!
> Really want to merge this in but we have a merge conflict. If you want, I
> am chilling in the Ruby room - I can help you fix this up [image: :+1:]
> 
> Otherwise if you want to try and to fix it up on your own, try following
> the instructions here to update your fork with the changes in upstream
> https://help.github.com/articles/syncing-a-fork
> 
> Either way is fine - lemmie know [image: :+1:]
> 
> [image: stoked]https://cloud.githubusercontent.com/assets/1024672/2560210/25c34cea-b7b1-11e3-8de5-d91fbac162c7.gif
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/railsgirlswgtn/animal-party/pull/27#issuecomment-39015519
> .

## 

_Rachel Collingridge_ _|_ 64 Donald Street, Karori, Wellington 6012, New
Zealand _| h: +64 4 476 7675 |_\* m: +64 021 755 374 | e:
rachel@collingridge.net rachel@collingridge.net*

**Comment by ammeep** [comment]
Sing out if you need a hand :heart: we are happy to help.

**Comment by missbassethorn** [comment]
Where are you?

I totally fudged it by just readding my changes to the latest file (I am
such a cheater)

On 30 March 2014 15:52, Amy Palamountain notifications@github.com wrote:

> Sing out if you need a hand [image: :heart:] we are happy to help.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/railsgirlswgtn/animal-party/pull/27#issuecomment-39016072
> .

## 

_Rachel Collingridge_ _|_ 64 Donald Street, Karori, Wellington 6012, New
Zealand _| h: +64 4 476 7675 |_\* m: +64 021 755 374 | e:
rachel@collingridge.net rachel@collingridge.net*

**Comment by ammeep** [comment]
I'll move to the bean bag room now!

**Comment by ammeep** [comment]
Nice job!! :heart:

**Pull request merged**
