### PR TITLE
Redpandas

### PR DESCRIPTION
**Pull request by thejduce**
Added pandas, pugs, cats, & meerkats. +1

### CODE REVIEW

**Comment by thejduce** [comment]
Resolved the merge conflict - @ammeep, can you have a look? Thanks!
puppy4

**Comment by ammeep** [comment]
Amazing :heart: nice job

inception

:ship:  it!!

**Comment by thejduce** [comment]
@ammeep I think burrito puppy is now sad he didn't get invited to the party.
kitten40

**Comment by ammeep** [comment]
Automatic merging is complicated :tm: 
Could you submit a new PR to invite him back to the party? :monkey_face:

**Pull request merged**
